version: '2'

networks:
  sola:

services:
  database.sola.com:
    image: sunderdocker/sola-database:1.0
    environment:
      - PGPORT=5444
    container_name: database.sola.com
    ports:
      - 5444:5444
    expose:
      - 5444
    networks:
      - sola

  database.init.sola.com:
    image: aequalis/sola-db:1.0
    environment:
      - DBHOST=database.sola.com
      - DBPORT=5444
    command: sh -c 'sleep 30 && /sola-db/create_database.sh'
    container_name: database.init.sola.com
    depends_on:
      - database.sola.com
    networks:
      - sola

  application.sola.com:
    image: sunderdocker/sola-application:1.0
    container_name: application.sola.com
    ports:
      - 8080:8080
      - 4848:4848
      - 8085:8085
      - 8181:8181
      - 4849:4849
    depends_on:
      - database.sola.com
    networks:
      - sola
